name: My first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4.1.7
  
      - name: welcome message
        run: echo "My first actions"
        
      - name: list files
        run: ls

      - name: Read File
        run: cat README.md

        # as it is yaml to write multi line command we have to use Pipe character
      - name: Running multiple command at once
        run: |
          echo "Hello World !"
          cat README.md
          ls -l

      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover, I am a Dragon...RAWR">> dragon.txt