name: My first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome message
        run: echo "My first actions"
        
      - name: list files
        run: ls

      - name: Read File
        run: cat README.md