name: Cowsays

on:
  push

jobs:
  Ascii_job:
    name: Cowsays
    runs-on: ubuntu-latest
    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4.1.7        

    #   - name: Ship it
    #     uses: mscoutermarsh/cowsays-action@master
    #     with:
    #       text: 'ship ship ship!'
    #       color: 'red'
    #   - name: Install cowsay
    #     run: sudo apt-get install cowsay -y

    #   - name: Execute Cowsay command
    #     run: cowsay -f dragon "Run for cover, I am a Dragon...RAWR">> dragon.txt
    #   - name: test file exists or not
    #     run: grep -i "dragon" dragon.txt
    #   - name: Read File
    #     run: cat dragon.txt
    #   - name: list all repo file
    #     run: ls -ltra


    # Running all above steps using a shell script
      - name: List all files in Repo
        run: ls -ltra
      - name: Executing shell script
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh