name: Matrix-Configuration-pipeline

# Controls when the workflow will run
on:
  push:
    branches: ["main", "neesh"]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

#A matrix strategy lets you use variables in a single job definition to automatically create 
# multiple job runs that are based on the combinations of the variables. 
# For example, you can use a matrix strategy to test your code in multiple versions of a language or on multiple operating systems.

jobs:
  build:
    strategy:
      # if we keep fail-fast as false then even if any one configuration fails build will continue
      fail-fast: false
      # using this we can control the no of jobs it runs at a time
      # max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest, mac-os]
        images: [hello-world, alpine]
        # As the alpine image fails on windows we will exclude it
        exclude:
          - images: alpine
            os: windows-latest
        include:
          - images: amd64/alpine
            os: ubuntu-20.04           
    runs-on: ${{matrix.os}}

    steps:
      - name: echo docker details
        run: docker info
      
      - name: Run Image on ${{matrix.os}}
        run: docker run ${{matrix.images}}