name: Matrix-Configuration-pipeline

# Controls when the workflow will run
on:
  push:
    branches: ["main", "neesh"]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

#A matrix strategy lets you use variables in a single job definition to automatically create 
# multiple job runs that are based on the combinations of the variables. 
# For example, you can use a matrix strategy to test your code in multiple versions of a language or on multiple operating systems.

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest, mac-os]
        images: [hello-world, alpine]
    runs-on: ${{matrix.os}}

    steps:
      - name: echo docker details
        run: docker info
      
      - name: Run Image on ${{matrix.os}}
        run: docker run ${{matrix.images}}