name: Multi_job_pipeline-using-expressions

on:
  workflow_dispatch: 

jobs:
  Job1:
    name: Build-Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4.1.7        

      - name: Install cowsay
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay command
        run: cowsay -f dragon "Run for cover, I am a Dragon...RAWR" >> dragon.txt
        
      - name: Test file exists or not
        run: grep -i "dragon" dragon.txt

      - name: Read File
        run: cat dragon.txt

      - name: List all repo files
        run: ls -ltra

      - name: Upload dragon file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt

  Job2:
    name: Test-Job
    runs-on: ubuntu-latest
    needs: Job1
    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4.1.7

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt

      - name: Test job
        continue-on-error: true
        run: grep -i "dragon" dragon.txt

  Job3:
    # added this expression so that deploy only runs on main
    name: Deploy-job
    if: github.ref == 'refs/heads/main'
    needs: [Job1, Job2]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt
      
      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploying
        run: echo "deploying ......"
