name: Variables-check-pipeline

on:
  push

jobs:
  Job1:
    name: Build-Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4.1.7        

        # This is example of step level env var declaration
      - name: Echo step level environment variable
        env:
          UserName: Neesh
          Role: Devops Engineer
        run: echo $UserName is $Role
