name: Variables-check-pipeline

on:
  workflow_dispatch:

env:
  workflowvar: Neesh
  messege1: This is a Workflow level environment variable

jobs:
  Job1:
    name: Build-Job
    runs-on: ubuntu-latest
    env:
      Developer: Neesh
      messege: This is a Job level environment variable
    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4.1.7        

      - name: Echo step level environment variable
        env:
          UserName: Neesh
          Role: DevOps Engineer
        run: |
          echo $UserName is $Role
          echo $Developer is $messege
      
      - name: Echo Job level environment variable
        run: echo $Developer is $messege

      - name: Echo Workflow level environment variable
        run: |
          echo $workflowvar is $messege1
          echo ${{ env.workflowvar }}

      - name: Echo Repo level variable and secrets
        run: |
          echo ${{ vars.REPO_DEVELOPER }}
          echo ${{ secrets.REPO_OWNER }}
